### ISSUE TITLE
Docker configuration not working

### ISSUE THREAD

**Issue by Xoeseko** [sdgsolutionspace/sdg-market-api#6] opened 2019-03-30 20:15 UTC
## Issue Summary
I'm trying to set up the app with `docker-compose up`. I can run both of them and reach both locally fine but when trying to dockerize both the frontend runs fine but the API just doesn't respond to requests. At worst I get redirected to the home page. How can I make the API accessible from my domain name /api/v1 ?

## Config
This is for an AWS server running amazon linux 2. I've tried it locally and it runs fine. The main issue is really connecting to the api on another docker instance from outside... Just to make sure I also tried on an amazon instance running ubuntu but the results weren't better I still needed to hack around the docker-compose.yml to make things work.

My docker-compose.yml
```yaml
version: '3'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: ${MYSQL_USER}
    stdin_open: true
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/mysql
    tty: true
    ports:
      - "3306:3306" #host:container

  cron:
    image: sdgsolspace/sdg-market-cron
    environment:
      MYSQL_HOST: db
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GITHUB_PARSER_LOGIN: ${GITHUB_PARSER_LOGIN}
      GITHUB_PARSER_PASSWORD: ${GITHUB_PARSER_PASSWORD}
      GITHUB_OAUTH_CLIENT_ID: ${GITHUB_OAUTH_CLIENT_ID}
      GITHUB_OAUTH_CLIENT_SECRET: ${GITHUB_OAUTH_CLIENT_SECRET}
    stdin_open: true
    tty: true
  
  sdg-market-api:
    image: sdgsolspace/sdg-market-api
    environment:
      MYSQL_HOST: db
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GITHUB_PARSER_LOGIN: ${GITHUB_PARSER_LOGIN}
      GITHUB_PARSER_PASSWORD: ${GITHUB_PARSER_PASSWORD}
      GITHUB_OAUTH_CLIENT_ID: ${GITHUB_OAUTH_CLIENT_ID}
      GITHUB_OAUTH_CLIENT_SECRET: ${GITHUB_OAUTH_CLIENT_SECRET}
    stdin_open: true
    tty: true
    ports:
      - "8000:8000" #host:container

  sdg-market-frontend:
    image: sdgsolspace/sdg-market-frontend
    environment:
      GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI}
      BASE_URL: ${BASE_URL}
      BASE_API_URL: ${BASE_API_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
    stdin_open: true
    tty: true
    ports:
      - "8001:80" #host:container
```

My .env file:

```
MYSQL_DB=ghtrading
MYSQL_USER=ghtrading
MYSQL_PASSWORD=ghtrading
GITHUB_PARSER_LOGIN=myusername
GITHUB_PARSER_PASSWORD=
GITHUB_OAUTH_CLIENT_ID=Iv1....
GITHUB_OAUTH_CLIENT_SECRET=8d9a...
GITHUB_CLIENT_ID=Iv1....
GITHUB_REDIRECT_URI=http://sdevs.ml/callback
BASE_URL=http://sdevs.ml
BASE_API_URL=http://sdevs.ml/api/v1/
DB_VOLUME_PATH=./database
```
## Expected results
I expected the given docker configuration to be virtually plug and play and at worst that setting the ports would help which it did for the frontend but the api is stil troublesome. By setting the ports as "8000:8000" for the api the endpoint should be accessible on port 8000 but on the one hand the /api/v1 url is not giving me anything it just goes back to the home page and on the other hand using the port number :8000 in the url gives me a denied cores request

EDIT : I now understand that the api was served by a proxy on /api/v1 so I configured my nginx instance as such

```
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  localhost sdevs.ml www.sdevs.ml;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location  ~ ^/api/v1/ {
            proxy_pass http://localhost:8000;
	    proxy_set_header Host $host;
	    #root /api/v1;
        }

	 location / {
            proxy_pass http://localhost:8001;
	}
}
```
Where still the frontend delivers fine but the api is still not cooperating...

**Comment by gilles-hemmerle** [comment] 2019-09-25 08:15
Do you still have this issue ? I think your are no longer using Docker for dev and the docker seems to work on the pre prod server. If you have still issues regarding the docker configuration, you can come back to Olivier and attach this ticket to him. If not, you can close this ticket.

**Comment by olivierb2** [comment] 2019-09-27 09:12
Okay, I guess you are getting the issue due to known right issue on the docker. I will have a look.

**Comment by olivierb2** [comment] 2019-09-27 11:35
Sorry, cannot reproduce the issue, work for the with docker-compose.

**Closed by olivierb2** 2019-09-27 11:36 UTC
